[package]
name = "rust-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.1.1", features = ["from", "display"] }
sha2 = "0.10.9"
wincode = "0.2.5"
wincode-derive = "0.2.3"
